# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'pictex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pictex
  pod 'Amplify'
  pod 'Amplify/Tools'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'

  target 'pictexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pictexUITests' do
    # Pods for testing
  end

end
